#!/bin/bash

mst start
mst status -v

# add some 2048Kb hugepages
sudo sysctl -w vm.nr_hugepages=100

# just in case, load modules needed
modprobe -a ib_uverbs mlx5_core mlx5_ib

# correct numa node
echo 0 > /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0/numa_node
echo 0 > /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.1/numa_node

# print the FW versions in the NICs:
echo mt4119_pciconf0 Firmware:
echo --------------------------------------------------------------
flint --qq -d /dev/mst/mt4119_pciconf0 query
echo
echo mt4119_pciconf0.1 Firmware:
echo --------------------------------------------------------------
flint --qq -d /dev/mst/mt4119_pciconf0.1 query
